name: tests
on: push

env:
  IMAGE_URL: https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2023-05-03/2023-05-03-raspios-bullseye-arm64-lite.img.xz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment variables
        run: |
          env

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create variables
        id: variables
        run: |
          echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT

          IMAGE_NAME=$(basename $IMAGE_URL | cut -d "." -f 1)
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

          IMAGE_CACHE_DIRECTORY="/var/cache/pimod/${IMAGE_URL#https://}"
          echo "image_cache_directory=$IMAGE_CACHE_DIRECTORY" >> $GITHUB_OUTPUT

          VERSION=$(cat VERSION)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.sha }})
          COMMIT_FIRST_LINE=$(echo "$COMMIT_MESSAGE" | tr ' ' '_' | tr '[:upper:]' '[:lower:]' | tr -d "[]")
          echo "commit_message=$COMMIT_FIRST_LINE" >> $GITHUB_OUTPUT

          echo "$IMAGE_NAME-v$VERSION-prod-$COMMIT_FIRST_LINE"

      - name: Save environment variables to file
        run: |
          sed -i "s|##IMAGE_URL##|${{ steps.variables.outputs.image_url }}|g" raspberry-pi-lite.Pifile
          sed -i "s|##IMAGE_NAME##|${{ steps.variables.outputs.image_name }}|g" raspberry-pi-lite.Pifile
          sed -i "s|##IMAGE_CACHE_DIRECTORY##|${{ steps.variables.outputs.image_cache_directory }}|g" raspberry-pi-lite.Pifile

      - name: Run pimod example
        uses: Nature40/pimod@master
        with:
          pifile: raspberry-pi-lite.Pifile

      - name: Compress
        run: |
          zip raspberry-pi-lite.img.zip raspberry-pi-lite.img
          mv hello hello-v${{ steps.variables.outputs.version }}-prod-${{ steps.variables.outputs.commit_message }}
          mv raspberry-pi-lite.img.zip ${{ steps.variables.outputs.image_name }}-v${{ steps.variables.outputs.version }}-prod-${{ steps.variables.outputs.commit_message }}.zip

      - name: Release when tags is available
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            hello-v${{ steps.variables.outputs.version }}-prod-${{ steps.variables.outputs.commit_message }}
            ${{ steps.variables.outputs.image_name }}-v${{ steps.variables.outputs.version }}-prod-${{ steps.variables.outputs.commit_message }}.zip
