name: tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run pimod example
        uses: Nature40/pimod@master
        with:
          pifile: RPi-RaspberryPiOSLite.Pifile
      - name: List files
        run: |
          echo "ls -la"
          echo ""
          ls -la

          echo "ls /"
          echo ""
          ls /

          echo "ls /home"
          echo ""
          ls /home
      - name: Compress the image
        run: |
          sudo xz RPi-RaspberryPiOSLite.img
      - name: Upload release image
        uses: actions/upload-artifact@v3
        with:
          name: Release image
          path: RPi-RaspberryPiOSLite.img.xz
