name: tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run pimod example
        uses: Nature40/pimod@master
        with:
          pifile: raspberry-pi-lite.Pifile
      - name: Upload release image
        uses: actions/upload-artifact@v3
        with:
          name: Release image
          path: raspberry-pi-lite.img
